### ISSUE TITLE
Here's something - or a couple of things - you might want to look at

### ISSUE THREAD

**Issue by electric-socket** [StanfordPascal/Pascal#3]
When I first looked at your compiler, I was rather amazed to discover it was around 25,000 lines, compared to, say, Pascal 8000 from the Australian Atomic Energy Commission, which I see you have a copy, as it's part of this repository, It's only about 6,000 lines, and one I've worked on, XDPascal, with the changes I made in my fork, is about 15,000 in about 8 files.

Then I discovered the Mad-Pascal compiler, https://github.com/tebe6502/Mad-Pascal, which is a pascal cross-compiler for the 6502 processor. Not counting include files, it clocks in at a single source file containing a whopping 45,000 lines! What is also interesting is it's written in plain non-object, non-extended Pascal. I'm investigating it closely, as I may steal pieces - or chunks of it - to update XDPascal. Or maybe just strip its code generator and refactor  XDPascal to generate code for it. 

I find these things fascinating, and I like trading how other  people developed solutions for whatever problem they had. I felt you might also be interested in this.

There is one other I found intriguing for a different reason. Ppro, an object-oriented Pascal compiler for MS-DOS. This computer does something that I find unusual: it handles nested comments, .e.g. {I have {something} to say}, and he does something I hadn't thought of, to handle them recursively. It's discovering things like these that allow me to admire some amazing work other people have done.

Thank you for reading,
Paul

**Comment by StanfordPascal** [comment]
Hi Paul, 

thank you for your comment; when I have time, I will look into these other compilers. 

First of all, I would like to mention, that my compiler (stage 1) today (2022) has about 25.000 lines, but when I started work in 2011, it also had only 6.000 lines. In 2017, I separated the symbol scanner into an extra source file, which makes 2.500 additional lines of code. And: there is the stage 2 part, which translates the generated P-Code from stage 1 to 370 machine code, with about 18.000 lines of code ... but we shouldn't probably count this, since it is not needed in non-Mainframe platforms. 

My compiler handles nested comments, too, but the feature is off by default and needs to be activated using a certain compiler option. Compiler options are specified using special comments; the "nested comment" option is N+ and must be specified like this:  \(\*$N+  \*\) - BTW: the nested comments are handled recursively in my compiler, too. 

You can activate the option anywhere in the program; when the compiler reads this comment, the option is activated. You can switch it off again by specifying \(\*$N- \*\) 

this should work with all types of comments, that is: {, /*. \(\*, // 

BTW: // works differently; the whole rest of the line is comment and the comment stops at the end of the line. No nesting is needed nor possible. 

Take care: no space allowed between the start of the comment and the dollar sign. 

You can set multiple options in one "option comment", for example: \(\*$N+,A+,D+   multiple options set \*\)

Maybe I should add a short help information to the compiler listing which shows all the possible options and the actual value of the option at the end of the compilation. 

Thanks for your interest in my compiler; have a nice day. 

Bernd
